/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    'ConfirmDelete.component': typeof import('./src/components/utils/ConfirmDelete.component.vue')['default']
    'HeaderMenu.component': typeof import('./src/components/HeaderMenu.component.vue')['default']
    HeaderMenuComponent: typeof import('./src/components/HeaderMenu.component.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'LoginForm.component': typeof import('./src/components/auth/LoginForm.component.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NForm: typeof import('naive-ui')['NForm']
    NForm_item: typeof import('naive-ui')['NForm_item']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NSpinner: typeof import('naive-ui')['NSpinner']
    NSplit: typeof import('naive-ui')['NSplit']
    NTable: typeof import('naive-ui')['NTable']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    'PokemonCard.component': typeof import('./src/components/pokemons/PokemonCard.component.vue')['default']
    'PokemonDeck.component': typeof import('./src/components/pokemons/PokemonDeck.component.vue')['default']
    PokemonGridComponent: typeof import('./src/components/PokemonGridComponent.vue')['default']
    'PokemonList.component': typeof import('./src/components/pokemons/PokemonList.component.vue')['default']
    'Register.component': typeof import('./src/components/Register.component.vue')['default']
    'RegisterForm.component': typeof import('./src/components/auth/RegisterForm.component.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    'SignIn.component': typeof import('./src/components/SignIn.component.vue')['default']
  }
}
